<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.ande1922.moduvera</groupId>
    <artifactId>moduvera-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>moduvera-architecture-testkit</artifactId>
  <name>Moduvera :: Testing :: Architecture TestKit</name>

  <dependencies>
    <dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit</artifactId>
      <version>${archunit.version}</version>
    </dependency>

    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-lock-local</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-message-core</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-auth-resource-server-autoconfigure</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-data-mybatis-plus-spring-boot-starter</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-scheduler-spring-boot-starter</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-web-spring-boot-starter</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>moduvera-messaging-kafka-spring-boot-starter</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>catalog-service</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>inventory-service</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>order-service</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>catalog-app</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>inventory-app</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>order-app</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>gateway-app</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.ande1922.moduvera</groupId>
      <artifactId>app-monolith</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <additionalClasspathElements>
            <additionalClasspathElement>${maven.multiModuleProjectDirectory}/apps/catalog-app/target/classes</additionalClasspathElement>
            <additionalClasspathElement>${maven.multiModuleProjectDirectory}/apps/inventory-app/target/classes</additionalClasspathElement>
            <additionalClasspathElement>${maven.multiModuleProjectDirectory}/apps/order-app/target/classes</additionalClasspathElement>
            <additionalClasspathElement>${maven.multiModuleProjectDirectory}/apps/gateway-app/target/classes</additionalClasspathElement>
            <additionalClasspathElement>${maven.multiModuleProjectDirectory}/apps/app-monolith/target/classes</additionalClasspathElement>
          </additionalClasspathElements>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
